apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lanbooking-api
  annotations:
    github.com/project-slug: rkuusisto/lanbooking-api
spec:
  type: other
  lifecycle: unknown
  owner: DataCodex
